//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inventory.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Adjustment.
        /// </summary>
        public static string AddAdjustment {
            get {
                return ResourceManager.GetString("AddAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Customer Consign.
        /// </summary>
        public static string AddCustomerConsign {
            get {
                return ResourceManager.GetString("AddCustomerConsign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Opening Stock.
        /// </summary>
        public static string AddOpeningStock {
            get {
                return ResourceManager.GetString("AddOpeningStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Purchase.
        /// </summary>
        public static string AddPurchase {
            get {
                return ResourceManager.GetString("AddPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Purchase Order.
        /// </summary>
        public static string AddPurchaseOrder {
            get {
                return ResourceManager.GetString("AddPurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Purchase Return.
        /// </summary>
        public static string AddPurchaseReturn {
            get {
                return ResourceManager.GetString("AddPurchaseReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Remark.
        /// </summary>
        public static string AddRemark {
            get {
                return ResourceManager.GetString("AddRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Sale Order.
        /// </summary>
        public static string AddSaleOrder {
            get {
                return ResourceManager.GetString("AddSaleOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Sale Return.
        /// </summary>
        public static string AddSaleReturn {
            get {
                return ResourceManager.GetString("AddSaleReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Transfer.
        /// </summary>
        public static string AddTransfer {
            get {
                return ResourceManager.GetString("AddTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment.
        /// </summary>
        public static string Adjustment {
            get {
                return ResourceManager.GetString("Adjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment List.
        /// </summary>
        public static string AdjustmentList {
            get {
                return ResourceManager.GetString("AdjustmentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Pay.
        /// </summary>
        public static string AdvancedPay {
            get {
                return ResourceManager.GetString("AdvancedPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Home.
        /// </summary>
        public static string BackToHome {
            get {
                return ResourceManager.GetString("BackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to POS.
        /// </summary>
        public static string BackToPOS {
            get {
                return ResourceManager.GetString("BackToPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        public static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank/Pay.
        /// </summary>
        public static string BankPay {
            get {
                return ResourceManager.GetString("BankPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        public static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges.
        /// </summary>
        public static string Charges {
            get {
                return ResourceManager.GetString("Charges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Sale Order.
        /// </summary>
        public static string ClientSaleOrder {
            get {
                return ResourceManager.GetString("ClientSaleOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ).
        /// </summary>
        public static string CloseParenthesis {
            get {
                return ResourceManager.GetString("CloseParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        public static string ColonSign {
            get {
                return ResourceManager.GetString("ColonSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consignment.
        /// </summary>
        public static string Consignment {
            get {
                return ResourceManager.GetString("Consignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        public static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Consign List.
        /// </summary>
        public static string CustomerConsignList {
            get {
                return ResourceManager.GetString("CustomerConsignList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dis.
        /// </summary>
        public static string Dis {
            get {
                return ResourceManager.GetString("Dis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        public static string Division {
            get {
                return ResourceManager.GetString("Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string DolorSign {
            get {
                return ResourceManager.GetString("DolorSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Note.
        /// </summary>
        public static string EnterNote {
            get {
                return ResourceManager.GetString("EnterNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Purchase Voucher No..
        /// </summary>
        public static string EnterPurchaseVoucherNo {
            get {
                return ResourceManager.GetString("EnterPurchaseVoucherNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Sale Voucher No..
        /// </summary>
        public static string EnterSaleVoucherNo {
            get {
                return ResourceManager.GetString("EnterSaleVoucherNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOC.
        /// </summary>
        public static string FOC {
            get {
                return ResourceManager.GetString("FOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Location.
        /// </summary>
        public static string FromLocation {
            get {
                return ResourceManager.GetString("FromLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grandtotal.
        /// </summary>
        public static string Grandtotal {
            get {
                return ResourceManager.GetString("Grandtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string HashSign {
            get {
                return ResourceManager.GetString("HashSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold.
        /// </summary>
        public static string Hold {
            get {
                return ResourceManager.GetString("Hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limited Day.
        /// </summary>
        public static string LimitedDay {
            get {
                return ResourceManager.GetString("LimitedDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Adjustment.
        /// </summary>
        public static string ListAdjustment {
            get {
                return ResourceManager.GetString("ListAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Customer Consign.
        /// </summary>
        public static string ListCustomerConsign {
            get {
                return ResourceManager.GetString("ListCustomerConsign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Opening Stock.
        /// </summary>
        public static string ListOpeningStock {
            get {
                return ResourceManager.GetString("ListOpeningStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Purchase.
        /// </summary>
        public static string ListPurchase {
            get {
                return ResourceManager.GetString("ListPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Purchase Order.
        /// </summary>
        public static string ListPurchaseOrder {
            get {
                return ResourceManager.GetString("ListPurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Purchase Return.
        /// </summary>
        public static string ListPurchaseReturn {
            get {
                return ResourceManager.GetString("ListPurchaseReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Sale.
        /// </summary>
        public static string ListSale {
            get {
                return ResourceManager.GetString("ListSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Sale Order.
        /// </summary>
        public static string ListSaleOrder {
            get {
                return ResourceManager.GetString("ListSaleOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Sale Return.
        /// </summary>
        public static string ListSaleReturn {
            get {
                return ResourceManager.GetString("ListSaleReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Transfer.
        /// </summary>
        public static string ListTransfer {
            get {
                return ResourceManager.GetString("ListTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Filter.
        /// </summary>
        public static string MenuFilter {
            get {
                return ResourceManager.GetString("MenuFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened Bills.
        /// </summary>
        public static string OpenedBills {
            get {
                return ResourceManager.GetString("OpenedBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Stock.
        /// </summary>
        public static string OpeningStock {
            get {
                return ResourceManager.GetString("OpeningStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Stock List.
        /// </summary>
        public static string OpeningStockList {
            get {
                return ResourceManager.GetString("OpeningStockList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (.
        /// </summary>
        public static string OpenParenthesis {
            get {
                return ResourceManager.GetString("OpenParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Method.
        /// </summary>
        public static string PayMethod {
            get {
                return ResourceManager.GetString("PayMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Type.
        /// </summary>
        public static string PayType {
            get {
                return ResourceManager.GetString("PayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent.
        /// </summary>
        public static string Percent {
            get {
                return ResourceManager.GetString("Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        public static string PercentSign {
            get {
                return ResourceManager.GetString("PercentSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS.
        /// </summary>
        public static string POS {
            get {
                return ResourceManager.GetString("POS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        public static string Purchase {
            get {
                return ResourceManager.GetString("Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase List.
        /// </summary>
        public static string PurchaseList {
            get {
                return ResourceManager.GetString("PurchaseList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order.
        /// </summary>
        public static string PurchaseOrder {
            get {
                return ResourceManager.GetString("PurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order List.
        /// </summary>
        public static string PurchaseOrderList {
            get {
                return ResourceManager.GetString("PurchaseOrderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Price.
        /// </summary>
        public static string PurchasePrice {
            get {
                return ResourceManager.GetString("PurchasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Return List.
        /// </summary>
        public static string PurchaseReturnList {
            get {
                return ResourceManager.GetString("PurchaseReturnList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuickInventory.
        /// </summary>
        public static string QuickInventory {
            get {
                return ResourceManager.GetString("QuickInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Change.
        /// </summary>
        public static string ReturnChange {
            get {
                return ResourceManager.GetString("ReturnChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Qty.
        /// </summary>
        public static string ReturnQty {
            get {
                return ResourceManager.GetString("ReturnQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Voucher No..
        /// </summary>
        public static string ReturnVoucherNo {
            get {
                return ResourceManager.GetString("ReturnVoucherNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        public static string Sale {
            get {
                return ResourceManager.GetString("Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Amount Only Report.
        /// </summary>
        public static string SaleAmountOnlyReport {
            get {
                return ResourceManager.GetString("SaleAmountOnlyReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Item Report.
        /// </summary>
        public static string SaleItemReport {
            get {
                return ResourceManager.GetString("SaleItemReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Item Simple Report.
        /// </summary>
        public static string SaleItemSimpleReport {
            get {
                return ResourceManager.GetString("SaleItemSimpleReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale List.
        /// </summary>
        public static string SaleList {
            get {
                return ResourceManager.GetString("SaleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Order.
        /// </summary>
        public static string SaleOrder {
            get {
                return ResourceManager.GetString("SaleOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Order List.
        /// </summary>
        public static string SaleOrderList {
            get {
                return ResourceManager.GetString("SaleOrderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Person.
        /// </summary>
        public static string SalePerson {
            get {
                return ResourceManager.GetString("SalePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Price.
        /// </summary>
        public static string SalePrice {
            get {
                return ResourceManager.GetString("SalePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Report.
        /// </summary>
        public static string SaleReport {
            get {
                return ResourceManager.GetString("SaleReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Return List.
        /// </summary>
        public static string SaleReturnList {
            get {
                return ResourceManager.GetString("SaleReturnList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Product.
        /// </summary>
        public static string SearchProduct {
            get {
                return ResourceManager.GetString("SearchProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Expired.
        /// </summary>
        public static string SessionExpired {
            get {
                return ResourceManager.GetString("SessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Status.
        /// </summary>
        public static string StockStatus {
            get {
                return ResourceManager.GetString("StockStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Status By Location.
        /// </summary>
        public static string StockStatusByLocation {
            get {
                return ResourceManager.GetString("StockStatusByLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        public static string Subtotal {
            get {
                return ResourceManager.GetString("Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspend Sale.
        /// </summary>
        public static string SuspendSale {
            get {
                return ResourceManager.GetString("SuspendSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        public static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Location.
        /// </summary>
        public static string ToLocation {
            get {
                return ResourceManager.GetString("ToLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Items.
        /// </summary>
        public static string TotalItems {
            get {
                return ResourceManager.GetString("TotalItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Pay.
        /// </summary>
        public static string TotalPay {
            get {
                return ResourceManager.GetString("TotalPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Purchase Items.
        /// </summary>
        public static string TotalPurchaseItems {
            get {
                return ResourceManager.GetString("TotalPurchaseItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Sale Items.
        /// </summary>
        public static string TotalSaleItems {
            get {
                return ResourceManager.GetString("TotalSaleItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer List.
        /// </summary>
        public static string TransferList {
            get {
                return ResourceManager.GetString("TransferList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Qty.
        /// </summary>
        public static string TransferQty {
            get {
                return ResourceManager.GetString("TransferQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Report.
        /// </summary>
        public static string ViewReport {
            get {
                return ResourceManager.GetString("ViewReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher Discount.
        /// </summary>
        public static string VoucherDiscount {
            get {
                return ResourceManager.GetString("VoucherDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher FOC.
        /// </summary>
        public static string VoucherFOC {
            get {
                return ResourceManager.GetString("VoucherFOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VoucherID.
        /// </summary>
        public static string VoucherID {
            get {
                return ResourceManager.GetString("VoucherID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher No..
        /// </summary>
        public static string VoucherNo {
            get {
                return ResourceManager.GetString("VoucherNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VouDis.
        /// </summary>
        public static string VouDis {
            get {
                return ResourceManager.GetString("VouDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VouFOC.
        /// </summary>
        public static string VouFOC {
            get {
                return ResourceManager.GetString("VouFOC", resourceCulture);
            }
        }
    }
}
