//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class SClient
    {
        public int ClientID { get; set; }
        public string ClientName { get; set; }
        public string ClientPassword { get; set; }
        public string ShopName { get; set; }
        public string Phone { get; set; }
        public Nullable<int> DivisionID { get; set; }
        public Nullable<int> TownshipID { get; set; }
        public string Address { get; set; }
        public Nullable<bool> IsSalePerson { get; set; }
        public string Token { get; set; }
    }
}
