//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class SStaff
    {
        public int StaffID { get; set; }
        public string Code { get; set; }
        public string StaffName { get; set; }
        public string Phone { get; set; }
        public Nullable<int> TownshipID { get; set; }
        public Nullable<int> DivisionID { get; set; }
        public string Address { get; set; }
    }
}
