//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class SVoucherFormat
    {
        public int ID { get; set; }
        public string PreFormat { get; set; }
        public string MidFormat { get; set; }
        public int PostFormat { get; set; }
        public string ModuleCode { get; set; }
    }
}
