//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCLMasterSaleOrder
    {
        public int SaleOrderID { get; set; }
        public Nullable<System.DateTime> OrderDateTime { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> Subtotal { get; set; }
        public Nullable<int> Tax { get; set; }
        public Nullable<int> TaxAmt { get; set; }
        public Nullable<int> Charges { get; set; }
        public Nullable<int> ChargesAmt { get; set; }
        public Nullable<int> Total { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsOrderFinished { get; set; }
    }
}
